<a href="https://colab.research.google.com/github/usaidahmed01/Deep-Learning/blob/master/30_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Corpus
# Each Sentence = Document
texts = [
    'I love this movie',
    'This film is amazing',
    'I enjoyed the movie',
    'I hate this movie',
    'This film was terrible',
    'I disliked the movie'
]
labels = [1, 1, 1, 0, 0 , 0]

In [2]:
# Tokenization
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=1000 , oov_token= '<OOV>') # oov_token means out of vocabulary

tokenizer.fit_on_texts(texts) # assign indexes on each word


In [3]:
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'i': 2, 'this': 3, 'movie': 4, 'film': 5, 'the': 6, 'love': 7, 'is': 8, 'amazing': 9, 'enjoyed': 10, 'hate': 11, 'was': 12, 'terrible': 13, 'disliked': 14}


In [4]:
# Convert Texts into sequences

sequences = tokenizer.texts_to_sequences(texts)
print(sequences)

[[2, 7, 3, 4], [3, 5, 8, 9], [2, 10, 6, 4], [2, 11, 3, 4], [3, 5, 12, 13], [2, 14, 6, 4]]


In [5]:
# Padding => for fixed input size
# Neural network ko fix dimension deni hain thats why

# we have done this Previously by vectorization function

# Two Types of padding pre and post
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = 6
X = pad_sequences(sequences , maxlen = max_length , padding = 'post')
y = labels


In [6]:
from tensorflow.keras.models import Sequential
from keras.layers import Embedding , Flatten, Dense

model = Sequential([
    Embedding(input_dim = 1000 , output_dim = 16 , input_length = max_length),
    # Embedding is basically converts word id into dense vector like convert into metrix
    Flatten(),
    # Flatten just make the metrix into 1 dimension
    Dense(16 , activation = 'relu'),
    Dense(1 , activation = 'sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [7]:
model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [8]:
import numpy as np
y = np.array(y)
history = model.fit(X , y , epochs = 30 , verbose = 2)

Epoch 1/30
1/1 - 1s - 1s/step - accuracy: 0.8333 - loss: 0.6884
Epoch 2/30
1/1 - 0s - 208ms/step - accuracy: 0.8333 - loss: 0.6863
Epoch 3/30
1/1 - 0s - 38ms/step - accuracy: 0.8333 - loss: 0.6844
Epoch 4/30
1/1 - 0s - 65ms/step - accuracy: 0.8333 - loss: 0.6827
Epoch 5/30
1/1 - 0s - 38ms/step - accuracy: 0.8333 - loss: 0.6809
Epoch 6/30
1/1 - 0s - 41ms/step - accuracy: 0.8333 - loss: 0.6794
Epoch 7/30
1/1 - 0s - 62ms/step - accuracy: 0.8333 - loss: 0.6778
Epoch 8/30
1/1 - 0s - 62ms/step - accuracy: 0.8333 - loss: 0.6763
Epoch 9/30
1/1 - 0s - 51ms/step - accuracy: 0.8333 - loss: 0.6746
Epoch 10/30
1/1 - 0s - 48ms/step - accuracy: 0.8333 - loss: 0.6728
Epoch 11/30
1/1 - 0s - 48ms/step - accuracy: 1.0000 - loss: 0.6711
Epoch 12/30
1/1 - 0s - 61ms/step - accuracy: 1.0000 - loss: 0.6693
Epoch 13/30
1/1 - 0s - 56ms/step - accuracy: 1.0000 - loss: 0.6674
Epoch 14/30
1/1 - 0s - 52ms/step - accuracy: 1.0000 - loss: 0.6655
Epoch 15/30
1/1 - 0s - 67ms/step - accuracy: 1.0000 - loss: 0.6635
Epoch

In [9]:
new_rev = ['I love this film',
           'This movie wsas horrible']

new_seq = tokenizer.texts_to_sequences(new_rev)
new_padded = pad_sequences(new_seq , maxlen = max_length , padding = 'post')
predictions = model.predict(new_padded)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[0.5277723]
 [0.5021459]]


In [10]:
# Save the model
model.save_weights('sentiment.weights.h5')
print('Done')

Done


In [12]:
# Re use the Same Model

new_model = Sequential([
    Embedding(input_dim = 1000 , output_dim = 16 , input_length = max_length),
    Flatten(),
    Dense(16 , activation = 'relu'),
    Dense(1 , activation = 'sigmoid')
])

new_model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
    )

new_model.build(input_shape = (None , max_length))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
new_model.load_weights('sentiment.weights.h5')


/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 12 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [14]:
new_model.save('sentiment_model.keras')

In [16]:
from tensorflow import keras
new_model = keras.models.load_model('sentiment_model.keras')


new_pred2 = new_model.predict(new_padded)
print(new_pred2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
[[0.5277723]
 [0.5021459]]


/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 12 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from keras.layers import Embedding , Flatten, Dense
import numpy as np

texts_practice = [
    'This album is a masterpiece, a true work of art from start to finish.',
    'Every track on this record is pure gold; I can\'t stop listening.',
    'The vocals are breathtaking, and the instrumentation is incredibly rich.',
    'A truly innovative sound that pushes the boundaries of the genre.',
    'This artist has outdone themselves; a career-defining album.',
    'I felt every emotion in these songs, truly captivating.',
    'The production quality is superb, crystal clear and powerful.',
    'An absolute must-listen for any music enthusiast.',
    'This album brought me so much joy; it\'s incredibly uplifting.',
    'I\'ve been waiting for a release like this for years; it\'s perfect.',
    'The beats are infectious, and the melodies are unforgettable.',
    'A fantastic blend of old-school vibes and modern flair.',
    'This record has quickly become my favorite of the year.',
    'The lyrics are deeply moving and thought-provoking.',
    'Such a vibrant and energetic album, perfect for any mood.',
    'I discovered so many new layers with each listen.',
    'The live performance of these tracks must be incredible.',
    'Truly a timeless piece of music, will be remembered for decades.',
    'I wholeheartedly recommend this to everyone; it\'s brilliant.',
    'A powerful and emotional journey from beginning to end.',
    'This album is a complete disappointment, utterly forgettable.',
    'I had high hopes, but this record fell completely flat.',
    'The singing is off-key, and the instruments sound muddy.',
    'A very generic and uninspired attempt at music.',
    'This artist has clearly lost their touch; a terrible release.',
    'I felt nothing while listening to these songs, utterly bland.',
    'The production quality is poor, sounds cheap and rushed.',
    'Avoid this album at all costs; a waste of time.',
    'This album brought me sadness; it\'s incredibly depressing.',
    'I wish I hadn\'t wasted my money on this; it\'s awful.',
    'The beats are monotonous, and the melodies are painful.',
    'A confusing mix of styles that just doesn\'t work.',
    'This record might be the worst of the year.',
    'The lyrics are shallow and repetitive.',
    'Such a dull and lifeless album, nothing exciting.',
    'I kept waiting for it to get good, but it never did.',
    'I can\'t imagine anyone enjoying this live.',
    'Just another forgettable release in a sea of mediocrity.',
    'I strongly advise against listening to this; it\'s dreadful.',
    'A chaotic and unpleasant experience from start to finish.',
    'The sound engineering is horrendous, a painful listen.',
    'This needs a full remix to be even remotely listenable.',
    'Their previous work was so much better, what happened?',
    'An embarrassment to the genre, truly awful.',
    'I wouldn\'t recommend this to my worst enemy.',
    'The album drags on forever, lacking any standout moments.',
    'Completely devoid of originality or creativity.',
    'A truly jarring and unpleasant auditory experience.',
    'This is background noise at best, nothing more.',
    'I\'m genuinely surprised this made it to release.'
]

labels_practice = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0
]

print(f"Generated {len(texts_practice)} practice texts and {len(labels_practice)} practice labels.")


Generated 50 practice texts and 50 practice labels.


## Summary:

### Data Analysis Key Findings
*   A new corpus of 50 mixed music reviews was created, consisting of 20 positive and 30 negative reviews, each with corresponding binary labels.
*   The practice texts were successfully preprocessed by tokenizing and padding them to a `max_length` of 6, after ensuring the `tokenizer` was properly initialized.
*   The `new_model` successfully generated sentiment predictions (probabilities) for the preprocessed practice corpus.
*   The model achieved an accuracy of 0.5400 on the newly created practice corpus.

### Insights or Next Steps
*   The accuracy of 0.5400 on the practice corpus suggests that the `new_model` performs only slightly better than random guessing for sentiment classification on this specific dataset, indicating poor generalization or an insufficient training corpus for music reviews.
*   To improve model performance, consider retraining the model on a substantially larger and more diverse dataset of music reviews. Additionally, explore more advanced NLP techniques or neural network architectures better suited for sentiment analysis.


In [ ]:
tokenizerP = Tokenizer(num_words = 2000 , oov_token='<OOV>')
tokenizerP.fit_on_texts(texts_practice)


word_indexes = tokenizerP.word_index
word_indexes

{'<OOV>': 1,
 'the': 2,
 'this': 3,
 'a': 4,
 'and': 5,
 'i': 6,
 'of': 7,
 'to': 8,
 'album': 9,
 'is': 10,
 'are': 11,
 'for': 12,
 "it's": 13,
 'truly': 14,
 'record': 15,
 'release': 16,
 'be': 17,
 'work': 18,
 'from': 19,
 'on': 20,
 'listening': 21,
 'incredibly': 22,
 'sound': 23,
 'has': 24,
 'these': 25,
 'listen': 26,
 'any': 27,
 'music': 28,
 'so': 29,
 'my': 30,
 'at': 31,
 'nothing': 32,
 'it': 33,
 'start': 34,
 'finish': 35,
 'every': 36,
 "can't": 37,
 'that': 38,
 'genre': 39,
 'artist': 40,
 'felt': 41,
 'in': 42,
 'songs': 43,
 'production': 44,
 'quality': 45,
 'powerful': 46,
 'an': 47,
 'must': 48,
 'brought': 49,
 'me': 50,
 'much': 51,
 'waiting': 52,
 'perfect': 53,
 'beats': 54,
 'melodies': 55,
 'year': 56,
 'lyrics': 57,
 'such': 58,
 'live': 59,
 'recommend': 60,
 'utterly': 61,
 'forgettable': 62,
 'but': 63,
 'completely': 64,
 'their': 65,
 'awful': 66,
 'painful': 67,
 'just': 68,
 'worst': 69,
 'unpleasant': 70,
 'experience': 71,
 'masterpiece': 72,

In [ ]:
sequencesOnText = tokenizerP.texts_to_sequences(texts_practice)
print(sequencesOnText)

[[3, 9, 10, 4, 72, 4, 73, 18, 7, 74, 19, 34, 8, 35], [36, 75, 20, 3, 15, 10, 76, 77, 6, 37, 78, 21], [2, 79, 11, 80, 5, 2, 81, 10, 22, 82], [4, 14, 83, 23, 38, 84, 2, 85, 7, 2, 39], [3, 40, 24, 86, 87, 4, 88, 89, 9], [6, 41, 36, 90, 42, 25, 43, 14, 91], [2, 44, 45, 10, 92, 93, 94, 5, 46], [47, 95, 48, 26, 12, 27, 28, 96], [3, 9, 49, 50, 29, 51, 97, 13, 22, 98], [99, 100, 52, 12, 4, 16, 101, 3, 12, 102, 13, 53], [2, 54, 11, 103, 5, 2, 55, 11, 104], [4, 105, 106, 7, 107, 108, 109, 5, 110, 111], [3, 15, 24, 112, 113, 30, 114, 7, 2, 56], [2, 57, 11, 115, 116, 5, 117, 118], [58, 4, 119, 5, 120, 9, 53, 12, 27, 121], [6, 122, 29, 123, 124, 125, 126, 127, 26], [2, 59, 128, 7, 25, 129, 48, 17, 130], [14, 4, 131, 132, 7, 28, 133, 17, 134, 12, 135], [6, 136, 60, 3, 8, 137, 13, 138], [4, 46, 5, 139, 140, 19, 141, 8, 142], [3, 9, 10, 4, 143, 144, 61, 62], [6, 145, 146, 147, 63, 3, 15, 148, 64, 149], [2, 150, 10, 151, 152, 5, 2, 153, 23, 154], [4, 155, 156, 5, 157, 158, 31, 28], [3, 40, 24, 159, 160

In [ ]:
max_length = 50

x = pad_sequences(sequencesOnText , max_length , padding = 'post')
y = np.array(labels_practice)

In [ ]:
modelP = Sequential([
    Embedding(input_dim = 2000 , output_dim= 16 , input_length = max_length),
    Flatten(),
    Dense(64 , activation = 'relu'),
    Dense(1 , activation = 'sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
modelP.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [ ]:
modelP.fit(x , y, epochs= 30 , verbose = 2)

Epoch 1/30
2/2 - 2s - 922ms/step - accuracy: 0.6000 - loss: 0.6808
Epoch 2/30
2/2 - 0s - 85ms/step - accuracy: 0.6000 - loss: 0.6671
Epoch 3/30
2/2 - 0s - 75ms/step - accuracy: 0.6000 - loss: 0.6625
Epoch 4/30
2/2 - 0s - 38ms/step - accuracy: 0.6000 - loss: 0.6638
Epoch 5/30
2/2 - 0s - 39ms/step - accuracy: 0.6000 - loss: 0.6577
Epoch 6/30
2/2 - 0s - 41ms/step - accuracy: 0.6000 - loss: 0.6512
Epoch 7/30
2/2 - 0s - 41ms/step - accuracy: 0.6000 - loss: 0.6465
Epoch 8/30
2/2 - 0s - 44ms/step - accuracy: 0.6000 - loss: 0.6377
Epoch 9/30
2/2 - 0s - 42ms/step - accuracy: 0.6000 - loss: 0.6312
Epoch 10/30
2/2 - 0s - 57ms/step - accuracy: 0.6000 - loss: 0.6241
Epoch 11/30
2/2 - 0s - 46ms/step - accuracy: 0.6000 - loss: 0.6143
Epoch 12/30
2/2 - 0s - 43ms/step - accuracy: 0.6000 - loss: 0.6065
Epoch 13/30
2/2 - 0s - 43ms/step - accuracy: 0.6400 - loss: 0.5915
Epoch 14/30
2/2 - 0s - 44ms/step - accuracy: 0.6400 - loss: 0.5779
Epoch 15/30
2/2 - 0s - 50ms/step - accuracy: 0.6400 - loss: 0.5631
Epo

In [ ]:
new_revB = ['This album is a complete disappointment, utterly forgettable',
            'This album is so good, like its a masterpiece']

new_rev_seq = tokenizerP.texts_to_sequences(new_revB)
new_rev_padd = pad_sequences(new_rev_seq , max_length , padding = 'post')

predictions = modelP.predict(new_rev_padd)
print(predictions)
print(['Good' if p >= 0.5 else 'bad' for p in predictions])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[0.12009695]
 [0.25812778]]
['bad', 'bad']
